---
repos:
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: "3.5.0"
  hooks:
  - id: editorconfig-checker
    args:
    - --exclude=LICENSE
# - repo: https://github.com/adrienverge/yamllint.git
#   rev: v1.37.1
#   hooks:
#   - id: yamllint
#     args:
#     - -c=./.yamllint
# https://github.com/google/yamlfmt/blob/main/docs/pre-commit.md
- repo: https://github.com/google/yamlfmt.git
  rev: v0.21.0
  hooks:
  - id: yamlfmt
    # In pre-commit we run yamlfmt in "lint" mode.
    # If you want to format the files, run `yamlfmt .` manually.
    args:
    - -lint
    - -quiet
    - -conf=./.yamlfmt
