---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.auth.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "powerdns.auth.labels" . | nindent 4 }}
  {{- with .Values.service.auth.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.auth.type }}
  ports: {{- toYaml .Values.service.auth.ports | nindent 2 }}
  selector:
    {{- include "powerdns.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.recursor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "powerdns.recursor.labels" . | nindent 4 }}
  {{- with .Values.service.recursor.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.recursor.type }}
  {{- if or (eq .Values.service.recursor.type "LoadBalancer") (eq .Values.service.recursor.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.recursor.externalTrafficPolicy }}
  {{- end }}
  ports: {{- toYaml .Values.service.recursor.ports | nindent 2 }}
  selector:
    {{- include "powerdns.selectorLabels" . | nindent 4 }}
